<a href="https://colab.research.google.com/github/sudharshanpaul/Machine-Learning/blob/main/EDA/FeatureScaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Feature Scaling

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/Churn_Modelling.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           9884 non-null   object 
 6   Age              9864 non-null   float64
 7   Tenure           9999 non-null   float64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(4), int64(7), object(3)
memory usage: 1.1+ MB


In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

***What is Normalization?***

Normalization is a scaling technique in which the values are shifted and rescaled so that they end up ranging between 0 and 1. It is also known as Min-Max Scaling

***What is Standardization?***

Standardization is another scaling technique where the values are centered around the mean with a unit standard deviation. This means that the mean of the attribute becomes zero and the resultant distribution has unit Standard deviation

In [ ]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female   NaN   
1          2    15647311      Hill          608     Spain  Female  41.0   
2          3    15619304      Onio          502    France  Female  42.0   
3          4    15701354      Boni          699    France  Female  39.0   
4          5    15737888  Mitchell          850     Spain     NaN   NaN   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0     2.0       0.00              1          1               1   
1     1.0   83807.86              1          0               1   
2     8.0  159660.80              3          1               0   
3     1.0       0.00              2          0               0   
4     2.0  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
df.describe().round(2) # which shows the statistical information of all the numerical values

RowNumber   CustomerId  CreditScore      Age   Tenure    Balance  \
count   10000.00     10000.00     10000.00  9864.00  9999.00   10000.00   
mean     5000.50  15690940.57       650.53    38.91     5.01   76485.89   
std      2886.90     71936.19        96.65    10.48     2.89   62397.41   
min         1.00  15565701.00       350.00    18.00     0.00       0.00   
25%      2500.75  15628528.25       584.00    32.00     3.00       0.00   
50%      5000.50  15690738.00       652.00    37.00     5.00   97198.54   
75%      7500.25  15753233.75       718.00    44.00     7.00  127644.24   
max     10000.00  15815690.00       850.00    92.00    10.00  250898.09   

       NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary   Exited  
count       10000.00   10000.00        10000.00         10000.00  10000.0  
mean            1.53       0.71            0.52        100090.24      0.2  
std             0.58       0.46            0.50         57510.49      0.4  
min             1.00       0.00            0.00            11.58      0.0  
25%             1.00       0.00            0.00         51002.11      0.0  
50%             1.00       1.00            1.00        100193.92      0.0  
75%             2.00       1.00            1.00        149388.25      0.0  
max             4.00       1.00            1.00        199992.48      1.0

*****NORMALIZATION*****

In [ ]:
df.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female   NaN   
1          2    15647311      Hill          608     Spain  Female  41.0   
2          3    15619304      Onio          502    France  Female  42.0   
3          4    15701354      Boni          699    France  Female  39.0   
4          5    15737888  Mitchell          850     Spain     NaN   NaN   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0     2.0       0.00              1          1               1   
1     1.0   83807.86              1          0               1   
2     8.0  159660.80              3          1               0   
3     1.0       0.00              2          0               0   
4     2.0  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
# Creating a new dataframe with the Age and Tenuew where we want to do the feature scaling using Normalization
new_df = pd.DataFrame(df,columns = ['Age','Tenure'])

In [ ]:
new_df.head(5)

Age  Tenure
0   NaN     2.0
1  41.0     1.0
2  42.0     8.0
3  39.0     1.0
4   NaN     2.0

In [ ]:
new_df.Age = new_df.Age.fillna(new_df.Age.mean())
new_df.Tenure = new_df.Tenure.fillna(df.Tenure.mean())

In [ ]:
new_df.isnull().sum()

Age       0
Tenure    0
dtype: int64

In [ ]:
scaler = MinMaxScaler() # Instantiating the MinMaxScaler() function
normalized_df = scaler.fit_transform(new_df)
print(normalized_df)

[[0.28263026 0.2       ]
 [0.31081081 0.1       ]
 [0.32432432 0.8       ]
 ...
 [0.24324324 0.7       ]
 [0.32432432 0.3       ]
 [0.28263026 0.4       ]]


In [ ]:
x_array = np.array([[2],[3],[5],[6],[6]])
scaler = MinMaxScaler()
normalized_arr = scaler.fit_transform(x_array)
normalized_arr

array([[0.  ],
       [0.25],
       [0.75],
       [1.  ],
       [1.  ]])

*****STANDARDIZATION*****

In [ ]:
scaler = StandardScaler()
standardized_df = scaler.fit_transform(new_df)
print(standardized_df)

[[-6.82605382e-16 -1.04173161e+00]
 [ 2.00336800e-01 -1.38751153e+00]
 [ 2.96404967e-01  1.03294792e+00]
 ...
 [-2.80004035e-01  6.87168000e-01]
 [ 2.96404967e-01 -6.95951688e-01]
 [-6.82605382e-16 -3.50171766e-01]]


In [ ]:
x_array = np.array([[2],[3],[5],[6],[6]])
scaler = StandardScaler()
standardized_arr = scaler.fit_transform(x_array)
standardized_arr

array([[-1.47709789],
       [-0.86164044],
       [ 0.36927447],
       [ 0.98473193],
       [ 0.98473193]])